Use `fly status` to lookup hostname
Old command no longer works, probably since https://github.com/superfly/flyctl/releases/tag/v0.1.21


    $ fly info --json
    Command "info" is deprecated, Replaced by 'status', 'ips list', and 'services list'

    ...

    Error: unknown flag: --json